version: '2'
services:
  nginx:
    image: ${NGINX_IMAGE}
    hostname: nginx
    volumes:
      - /tmp/mnt/certs:/etc/nginx/certs
      - /tmp/mnt/etc:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR}:/var/log/nginx
    ports:
      - "${VM1_EXTERNAL_IP}:${NGINX_PORT}:443"
